### ISSUE TITLE
Error when using GPU for pruning

### ISSUE THREAD

**Issue by Daisy5296** [horseee/LLM-Pruner#4]
Hi when I try to implement the following:

python hf_prune.py --pruning_ratio 0.25 --block_wise --block_mlp_layer_start 4 --block_mlp_layer_end 30 --block_attention_layer_start 4 --block_attention_layer_end 30 --pruner_type taylor --test_after_train --device cuda  --eval_device cuda --save_ckpt_log_name  lama_prune

I got an error:
Traceback (most recent call last):
  File "hf_prune.py", line 296, in <module>
    main(args)
  File "hf_prune.py", line 129, in main
    loss = model(example_prompts, labels=example_prompts).loss
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dfs/data/LLM-Pruner/LLMPruner/models/hf_llama/modeling_llama.py", line 689, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dfs/data/LLM-Pruner/LLMPruner/models/hf_llama/modeling_llama.py", line 532, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2156, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

Is it not supported for GPU pruning?

PS., May I ask that how much memory is needed overall?

**Comment by horseee** [comment]
Hi. I update the code to fix the bug☺️

If you use the Taylor pruner, the GPU memory requirement relies on factors such as the base model's size, the number of samples, and the sequence length specified in `example_inputs' in Line 127 of hf_pruner.py. Reproducing the results mentioned in the paper would necessitate more than 80GB of memory. Thus, we offer instructions for execution on CPU, as the backward process needs to be computed only once. Even when executed on a CPU, the process will be completed within two to three minutes.

**Comment by Daisy5296** [comment]
Thanks! May I ask how much memory is needed when implement on CPU? I always got killed when using CPU....that's why I was trying to use GPU...lol

**Comment by horseee** [comment]
I conducted a test using the command you specified earlier, and it consumed 79.7GB of CPU memory.

**Comment by Daisy5296** [comment]
Thanks, I manage to run hf_prune.py. But another problem when I ran post_training.py... Could you please help to have a look? Thanks in advance! 

Specifically, the "yahma/alpaca-cleaned" dataset can not be load correctly. I have downloaded the dataset (https://huggingface.co/datasets/yahma/alpaca-cleaned/tree/main) on my disk, and use the following command to load it:

data = load_dataset("/dfs/data/alpaca-cleaned")

where the path is my local directory storing the downloaded dataset. Then I got the following error:

Using custom data configuration alpaca-cleaned-e0e6b706b5460be0
Downloading and preparing dataset json/alpaca-cleaned to /root/.cache/huggingface/datasets/json/alpaca-cleaned-e0e6b706b5460be0/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253...
Downloading data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 931.24it/s]
Extracting data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 316.67it/s]
0 tables [00:00, ? tables/s]Failed to read file '/dfs/data/alpaca-cleaned/alpaca_data_cleaned.json' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Column() changed from object to array in row 0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/datasets/packaged_modules/json/json.py", line 110, in _generate_tables
    io.BytesIO(batch), read_options=paj.ReadOptions(block_size=block_size)
  File "pyarrow/_json.pyx", line 246, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Column() changed from object to array in row 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/datasets/load.py", line 1751, in load_dataset
    use_auth_token=use_auth_token,
  File "/opt/conda/lib/python3.6/site-packages/datasets/builder.py", line 705, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/opt/conda/lib/python3.6/site-packages/datasets/builder.py", line 793, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/datasets/builder.py", line 1275, in _prepare_split
    generator, unit=" tables", leave=False, disable=(not logging.is_progress_bar_enabled())
  File "/opt/conda/lib/python3.6/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.6/site-packages/datasets/packaged_modules/json/json.py", line 135, in _generate_tables
    f"Not able to read records in the JSON file at {file}. "
AttributeError: 'list' object has no attribute 'keys'

**Comment by wefwefWEF2** [comment]
Hi， thanks for your work, and I have some problems，


python //code/mini/LLM-Pruner/hf_prune.py --pruning_ratio 0.25 \
      --block_wise \
      --block_mlp_layer_start 4 --block_mlp_layer_end 30 \
      --block_attention_layer_start 4 --block_attention_layer_end 30 \
      --pruner_type taylor \
      --test_after_train \
      --device cpu  --eval_device cpu \
      --save_ckpt_log_name llama_prune 

use cpu for eval，I find it costs more than 3 hours，
use GPU for eval; my device is 1 A100  with 80g， which is still not enough; more A100 seems useless; it does not support.

Could you please tell me your device for eval， and how to run on multi-gpus, thanks a lot.
