### ISSUE TITLE
OSError: Can't load tokenizer for 'baffo32/decapoda-research-llama-7B-hf'.

### ISSUE THREAD

**Issue by qxpBlog** [horseee/LLM-Pruner#47]
bash scripts/llama_prune.sh

[START] - Start Pruning Model
Traceback (most recent call last):
  File "/home/iotsc01/xinpengq/LLM-Pruner-main/hf_prune.py", line 314, in <module>
    main(args)
  File "/home/iotsc01/xinpengq/LLM-Pruner-main/hf_prune.py", line 39, in main
    tokenizer = LlamaTokenizer.from_pretrained(args.base_model)
  File "/home/iotsc01/anaconda3/envs/xinpengq_env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2012, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'baffo32/decapoda-research-llama-7B-hf'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'baffo32/decapoda-research-llama-7B-hf' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.
[FINISH] - Finish Pruning Model
[START] - Start Tuning
Traceback (most recent call last):
  File "/home/iotsc01/xinpengq/LLM-Pruner-main/post_training.py", line 262, in <module>
    main(args)
  File "/home/iotsc01/xinpengq/LLM-Pruner-main/post_training.py", line 33, in main
    pruned_dict = torch.load(args.prune_model, map_location='cpu')
  File "/home/iotsc01/anaconda3/envs/xinpengq_env/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/iotsc01/anaconda3/envs/xinpengq_env/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/iotsc01/anaconda3/envs/xinpengq_env/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'prune_log/llama_prune/pytorch_model.bin'
[FINISH] - Finish Prune and Post-Training.
[INFO] - The pruned model is at {prune_log/llama_prune/pytorch_model.bin}, and the recovery weight is at {tune_log/llama_0.2}/
You can use the command:
       python generate.py --model_type tune_prune_LLM --ckpt prune_log/llama_prune/pytorch_model.bin --lora_ckpt tune_log/llama_0.2
to use the pruned model

**Comment by qxpBlog** [comment]
@horseee 您知道这是什么原因造成的吗，我在llama_pune.sh中添加上了--base_model baffo32/decapoda-research-llama-7B-hf这个参数，但是还是报错

**Comment by BrownTan** [comment]
一样的问题，请问您解决了吗

**Comment by BrownTan** [comment]
原来你也是uestcer
