### ISSUE TITLE
Adaptation of GQA

### ISSUE THREAD

**Issue by junzhang-zj** [horseee/LLM-Pruner#64]
Thank you for your solid work. I would like to ask if the current version is suitable for GQA architecture models, such as LLaMA-2-70B and LLaMA-3.

**Comment by junzhang-zj** [comment]
thanks!Ma Xinyin ***@***.***>于2024年7月25日 周四18:28写道：
Hi,
Thanks for your interest in our paper. Currently not, we tested it and it has some bugs in the code.
We are currently working on the support of LLM-Pruner for Llama3 and Llama-3.1, and it would take some time before we can release it (Most likely in this week).

**Comment by horseee** [comment]
Hi, 

The code supports GQA now. Here is the [command](https://github.com/horseee/LLM-Pruner?tab=readme-ov-file#llama-llama3llama31-pruning) and some of the [results](https://github.com/horseee/LLM-Pruner/tree/main/more_results)

**Comment by junzhang-zj** [comment]
Thanks, I'm using it now! But when I try param_mix on 70b, it gets aborted, while when I run param_first on the CPU, it works fine, albeit slower. I have another question, is there a specific reason for pruning based on k proj? Why not try to fix k and v, and prune q and o at a fixed ratio every 8 heads?

**Comment by RamitPahwa** [comment]
What are the memory requirements to run the code, I face OOM on 40GB A100, if I set my device to `cuda` instead of `cpu` , which is extremely slow, Is there a workaround to make it faster.

**Comment by junzhang-zj** [comment]
@RamitPahwa For the current version, it seems that for large models, normal pruning can only be done through the CPU.

**Comment by horseee** [comment]
> What are the memory requirements to run the code, I face OOM on 40GB A100, if I set my device to `cuda` instead of `cpu` , which is extremely slow, Is there a workaround to make it faster.

Hi @RamitPahwa, 

I met the same issue when I tried to prune llama-3. The pruning needs a GPU with 80GB of memory, and I'm not sure the reason for its extremely slow speed on CPUs. Perhaps some bugs in my code......

**Comment by baldwin6** [comment]
Hello, I have some problems with pruning on llama3. When the pruning ratio is less than 0.1, an error will be reported as follows：
Traceback (most recent call last):
  File "/public/home/ljt/xy/prune_llm/LLM-Pruner-main/llama3.py", line 317, in <module>
    main(args)
  File "/public/home/ljt/xy/prune_llm/LLM-Pruner-main/llama3.py", line 155, in main
    pruner.step()
  File "/public/home/ljt/xy/prune_llm/LLM-Pruner-main/LLMPruner/torch_pruning/pruner/algorithms/metapruner.py", line 186, in step
    for group in self.prune_local():
  File "/public/home/ljt/xy/prune_llm/LLM-Pruner-main/LLMPruner/torch_pruning/pruner/algorithms/metapruner.py", line 276, in prune_local
    pruning_idxs = torch.cat(
RuntimeError: torch.cat(): expected a non-empty list of Tensors
I sincerely look forward to your response！
