### ISSUE TITLE
RuntimeError of test_speedup.py

### ISSUE THREAD

**Issue by Daisy5296** [horseee/LLM-Pruner#7]
Hi! I ran the following command:
python test_speedup.py --model_type pruneLLM --base_model ../llama-7b-hf --ckpt prune_log/llama_prune/pytorch_model.bin

and got the following error:
Warning: module Embedding is treated as a zero-op.
Warning: module LlamaRotaryEmbedding is treated as a zero-op.
Warning: module LlamaMLP is treated as a zero-op.
Warning: module LlamaDecoderLayer is treated as a zero-op.
Warning: module LlamaModel is treated as a zero-op.
Warning: module LlamaForCausalLM is treated as a zero-op.
Traceback (most recent call last):
  File "test_speedup.py", line 91, in <module>
    main(args)
  File "test_speedup.py", line 69, in main
    macs, params = get_model_complexity_info(model, (64,), as_strings=True,
  File "/opt/conda/lib/python3.8/site-packages/ptflops/flops_counter.py", line 30, in get_model_complexity_info
    flops_count, params_count = get_flops_pytorch(model, input_res,
  File "/opt/conda/lib/python3.8/site-packages/ptflops/pytorch_engine.py", line 44, in get_flops_pytorch
    _ = flops_model(batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1128, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/dfs/data/LLM-Pruner/LLMPruner/models/hf_llama/modeling_llama.py", line 689, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dfs/data/LLM-Pruner/LLMPruner/models/hf_llama/modeling_llama.py", line 532, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2156, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.HalfTensor instead (while checking arguments for embedding)

Could you please help to have a look?

**Comment by horseee** [comment]
Hi. The test_speedup.py only supports the testing on GPU currently. Have you tested this script on GPU?

**Comment by horseee** [comment]
Hi. We update the test_speedup.py to support the testing on GPU. 
Please let me know if the bug still exists with the current version.

**Comment by sbwww** [comment]
Are there official FLOPs statistics on LLaMa-7B and its pruned version?

**Comment by sbwww** [comment]
> The FLOPs of the base model and the pruned model are: <img alt="image" width="413" src="https://user-images.githubusercontent.com/22924514/252266347-5bf98ba9-a4a9-4094-8216-2f6e2a1e77a4.png">

here #MACs is equivalent to #FLOPs right? I just thought that they could be two different things.

**Comment by horseee** [comment]
> > The FLOPs of the base model and the pruned model are: <img alt="image" width="413" src="https://user-images.githubusercontent.com/22924514/252266347-5bf98ba9-a4a9-4094-8216-2f6e2a1e77a4.png">
> 
> here #MACs is equivalent to #FLOPs right? I just thought that they could be two different things.

The results presented in the table is MACs rather than FLOPs and we didn't calculated the exact `FLOPs` of the model (roughly 2 times of MACs). To prevent any potential confusion, we chose not to use the term 'FLOPs' in our paper, and thus all the results are MACs and not equivalent to FLOPs.

**Comment by Daisy5296** [comment]
> Hi. The test_speedup.py only supports the testing on GPU currently. Have you tested this script on GPU?

Hi thanks for reply! Actually I was using GPU to run this code before. 

Now I've tried the new version, when ran on CPU it worked fine. But if ran on GPU, the same error still existed.

**Comment by Daisy5296** [comment]
Thanks for rapid reply! I've also made the same corrections following your code for the CPU implementations, and it works now. Thanks again!
