### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1

### ISSUE THREAD

**Issue by BrownTan** [horseee/LLM-Pruner#77]
Have some people met this problem?
I know it's because of the dataset being loaded, and it's possible that it's a version issue or a gzip archive issue.
But I don't know how to modify it.
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/node6_1/tanshuai/LLM-Pruner/hf_prune.py", line 314, in <module>
    main(args)
  File "/node6_1/tanshuai/LLM-Pruner/hf_prune.py", line 128, in main
    example_prompts = get_examples('bookcorpus', tokenizer, args.num_examples, seq_len = 64).to(args.device)
  File "/node6_1/tanshuai/LLM-Pruner/LLMPruner/datasets/example_samples.py", line 51, in get_examples
    return get_bookcorpus(tokenizer, n_samples, seq_len)
  File "/node6_1/tanshuai/LLM-Pruner/LLMPruner/datasets/example_samples.py", line 38, in get_bookcorpus
    i = random.randint(0, len(traindata) - 1)`

**Comment by BrownTan** [comment]
Oh,my god.It's because I didn't open my clash.

**Comment by VincentZ-2020** [comment]
> Oh,my god.It's because I didn't open my clash.

I also met this,  please tell me how to fix this?

**Comment by BrownTan** [comment]
> > Oh,my god.It's because I didn't open my clash.
> 
> I also met this, please tell me how to fix this?

You need a VPN.

**Comment by VincentZ-2020** [comment]
> > > Oh,my god.It's because I didn't open my clash.
> > 
> > 
> > I also met this, please tell me how to fix this?
> 
> You need a VPN.
Downgrading to datasets==2.14.6 is useful.
Refer to this https://github.com/huggingface/datasets/issues/6760#issuecomment-2041390144
